name: '📋 Gemini Scheduled Issue Triage'

on:
  workflow_dispatch:

jobs:
  triage:
    permissions:
      contents: 'read'
      id-token: 'write'
      issues: 'write'
      pull-requests: 'write'
    uses: \1v1.10
    secrets: inherit
