name: Gemini Auto PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  gemini-review:
    permissions:
      contents: 'read'
      pull-requests: 'write'
      issues: 'write'
      id-token: 'write'
    uses: '\1v1.10'
    with:
      pr_number: '${{ github.event.pull_request.number }}'
    secrets: 'inherit'
