name: OpenCode

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  opencode:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: jhw7500/automation/.github/workflows/opencode.yml@3bd490954b1db981258dce8d670d7511507ddc80
    secrets:
      ZHIPU_API_KEY: ${{ secrets.ZHIPU_API_KEY }}
