name: OpenCode

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  opencode:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: jhw7500/automation/.github/workflows/opencode.yml@444a7347aee169ed178aae80e8bd8d10eca52e02
    secrets:
      ZHIPU_API_KEY: ${{ secrets.ZHIPU_API_KEY }}
