name: OpenCode

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  opencode:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: jhw7500/automation/.github/workflows/opencode.yml@136e377eb5d3c91aff2a025d4b389c5e9d9de528
    secrets:
      ZHIPU_API_KEY: ${{ secrets.ZHIPU_API_KEY }}
